---
apiVersion: v1
kind: Pod
metadata:
  name: back
  labels:
    app: back-svc
spec:
  containers:
    - name: nginx
      image: nginx:1.19.1
---
apiVersion: v1
kind: Service
metadata:
  name: back-svc
spec:
  selector:
    app: back-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
